In [1]:
import pandas as pd
import numpy as np
from Bio import SeqIO
from Bio.SeqRecord import SeqRecord
from Bio import AlignIO
import os
import pathlib

In [2]:
os.chdir("/home/kaderi/Feroj/thesis/HRV-C/Data_collecton/hrv-top5/result_collection")

In [44]:
alignment_vp1 = AlignIO.read("/home/kaderi/Feroj/thesis/HRV-C/Data_collecton/hrv-top5/vp2_aligned.fasta", "fasta")
print(alignment_vp1)
print(alignment_vp1.get_alignment_length())

Alignment with 5 rows and 211 columns
TTQDSLNTVVAYGEWPEYLSDLDATSVDKPTHPETSSDRFYTLE...PLR HRV-C2_VP2
TTQDAVNTIVAYGEWPSYLSDMDATSVDKPTHPETSSDRFYTLN...PLR HRV-C6_VP2
TTQDTLNTIVAYGEWPSYLADIDATSVDKPTHPETSADRFYTLD...PLR HRV-C9_VP2
-TQDSLHTVLAYGEWPTYLSDIDATSVDKPTHPETSADRFYTLD...PLR HRV-C15_VP2
TTQDAVNTIVAYGEWPSYLSDLDATSVDKPTHPETSSDRFYTLE...PLR HRV-C43_VP2
211

In [45]:

consensus_sequence = ""
for residue in range(0,alignment_vp1.get_alignment_length()):
    unique_chars = ""
    for i in alignment_vp1[:,residue]:
        if i in unique_chars:
            pass
        else:
            unique_chars+=i
    char_dict = dict()

    for j in unique_chars:

        char_dict.update({f"{j}":alignment_vp1[:,residue].count(j)})


    keys = char_dict.keys()
    if '-' in keys:
        char_dict.pop("-")

    dict_value= list(char_dict.values())

    for keys, values in char_dict.items():
        if values == max(dict_value):
            consensus_sequence += keys
            break

                    

print(consensus_sequence)
print(len(consensus_sequence))

TTQDSLNTIVAYGEWPSYLSDLDATSVDKPTHPETSSDRFYTLESVTWQGSSRGWWWKLPDCLKDMGVFGQNMYHHSMGRSGYIIHTQCNATKFHSGCLLVAVVPEHQLAYIGGGGVNVKYEHTHPGEGGHRIRGPGASNDRSNNNPDEDPFFNCNGTLLGNLTIFPHQMINLRTNNSSTIVVPYINCVPMDNMLRHNNVSLVIIPIVPLR
211

In [46]:
conserved = ""
for i in range(alignment_vp1.get_alignment_length()):
    column = alignment_vp1[:, i]
    if column.count(column[0]) == len(column) and column[0] != "-":
        conserved += column[0]
    else:
        conserved += "-"

print("Conserved pattern:\n", conserved)
print(len(conserved))

Conserved pattern:
 -TQD---T--AYGEWP-YL-D-DATSVDKPTHPETS-DRFYTL-SV-W---S-GWWWK-PD-L-DMG-FGQNMY-H-MGRSG---H-QCNATKFHSG-L-V-V-PEHQL-Y-G-----V-Y-HTHPG--GH----------R----PDE-P---CNGTL-GN--I-PHQ-INLRTNNS-TIV-PYINC-PMD-ML-HNN--L-IIP--PLR
211

In [47]:
conserve_epitops= []
for i in conserved.split("-"):
    if len(i)>=5:
        conserve_epitops.append(i)
    else:
        pass
conserve_epitops

['AYGEWP',
 'DATSVDKPTHPETS',
 'DRFYTL',
 'GWWWK',
 'FGQNMY',
 'MGRSG',
 'QCNATKFHSG',
 'PEHQL',
 'HTHPG',
 'CNGTL',
 'INLRTNNS',
 'PYINC']

In [69]:
long_epitope = "FPHQMINLRTNNSSTIVV"
len(long_epitope)

18

In [62]:
epitope_breaker = []
f = 0
l = 20

for i in range(f,len(long_epitope)):

    epitope_breaker.append(long_epitope[f:l])
    l += 1
    f += 1

    if l == len(long_epitope)+1:
        break

In [63]:
epitope_breaker

['YKDAASSGLTKQDFSQDPSK',
 'KDAASSGLTKQDFSQDPSKF',
 'DAASSGLTKQDFSQDPSKFT',
 'AASSGLTKQDFSQDPSKFTQ',
 'ASSGLTKQDFSQDPSKFTQP',
 'SSGLTKQDFSQDPSKFTQPV',
 'SGLTKQDFSQDPSKFTQPVA',
 'GLTKQDFSQDPSKFTQPVAD',
 'LTKQDFSQDPSKFTQPVADV',
 'TKQDFSQDPSKFTQPVADVL',
 'KQDFSQDPSKFTQPVADVLT',
 'QDFSQDPSKFTQPVADVLTN']

In [64]:
conserve_epitops = ['GAQVS', 'NYYKD', 'ASSGL', 'QDFSQDPSKFTQP', 'NPALM']
breaker_frame = pd.DataFrame({"conserve_epitops":[],
                             "epitopes":[]})
conserve_epitopes_breaker = []
conserve_epitopes_breaker_filtered = []

for a in conserve_epitops:
    for b in epitope_breaker:
        if a in b:
            conserve_epitopes_breaker.append(a)
            conserve_epitopes_breaker_filtered.append(b)
breaker_frame_1 = pd.DataFrame({"conserve_epitops":conserve_epitopes_breaker,
                         "epitopes":conserve_epitopes_breaker_filtered}) 
            
breaker_frame = pd.concat((breaker_frame,breaker_frame_1),ignore_index= True)

breaker_frame

   conserve_epitops              epitopes
0             ASSGL  YKDAASSGLTKQDFSQDPSK
1             ASSGL  KDAASSGLTKQDFSQDPSKF
2             ASSGL  DAASSGLTKQDFSQDPSKFT
3             ASSGL  AASSGLTKQDFSQDPSKFTQ
4             ASSGL  ASSGLTKQDFSQDPSKFTQP
5     QDFSQDPSKFTQP  ASSGLTKQDFSQDPSKFTQP
6     QDFSQDPSKFTQP  SSGLTKQDFSQDPSKFTQPV
7     QDFSQDPSKFTQP  SGLTKQDFSQDPSKFTQPVA
8     QDFSQDPSKFTQP  GLTKQDFSQDPSKFTQPVAD
9     QDFSQDPSKFTQP  LTKQDFSQDPSKFTQPVADV
10    QDFSQDPSKFTQP  TKQDFSQDPSKFTQPVADVL
11    QDFSQDPSKFTQP  KQDFSQDPSKFTQPVADVLT
12    QDFSQDPSKFTQP  QDFSQDPSKFTQPVADVLTN

In [65]:
breaker_frame[breaker_frame.duplicated(subset=('epitopes'))]

  conserve_epitops              epitopes
5    QDFSQDPSKFTQP  ASSGLTKQDFSQDPSKFTQP

In [66]:
breaker_frame[breaker_frame['epitopes']=='VFGQNMYHHSMGRSGYIIHT']

Empty DataFrame
Columns: [conserve_epitops, epitopes]
Index: []

In [67]:
conserve_epitopes_breaker = []
conserve_epitopes_breaker_filtered = []
for i in breaker_frame["epitopes"].unique():
    index_conserve = breaker_frame[breaker_frame["epitopes"]== i ]['conserve_epitops'].values
    # presence_conserve = breaker_frame[breaker_frame["candidate_epitope"]== i ]['conservence_presence'].values
    conserve_epitope_region_table = ''
    # conserve_epitope_presence_table = ''
    if len(index_conserve)> 1:
        for j in index_conserve:
            conserve_epitope_region_table += f"{j}"
            conserve_epitope_region_table += ","
        # for k in presence_conserve:
        #     conserve_epitope_presence_table += f"{k}"
        #     conserve_epitope_presence_table += ","
    else:
        conserve_epitope_region_table += f"{index_conserve[0]}"
        # conserve_epitope_presence_table += f"{presence_conserve[0]}"
    conserve_epitopes_breaker.append(i)
    conserve_epitopes_breaker_filtered.append(conserve_epitope_region_table)
    # conserve_epitope_presence.append(conserve_epitope_presence_table)

In [68]:
final_epitopes =  pd.DataFrame({'epitopes':conserve_epitopes_breaker,
                                'conserve_residue':conserve_epitopes_breaker_filtered})
final_epitopes

                epitopes      conserve_residue
0   YKDAASSGLTKQDFSQDPSK                 ASSGL
1   KDAASSGLTKQDFSQDPSKF                 ASSGL
2   DAASSGLTKQDFSQDPSKFT                 ASSGL
3   AASSGLTKQDFSQDPSKFTQ                 ASSGL
4   ASSGLTKQDFSQDPSKFTQP  ASSGL,QDFSQDPSKFTQP,
5   SSGLTKQDFSQDPSKFTQPV         QDFSQDPSKFTQP
6   SGLTKQDFSQDPSKFTQPVA         QDFSQDPSKFTQP
7   GLTKQDFSQDPSKFTQPVAD         QDFSQDPSKFTQP
8   LTKQDFSQDPSKFTQPVADV         QDFSQDPSKFTQP
9   TKQDFSQDPSKFTQPVADVL         QDFSQDPSKFTQP
10  KQDFSQDPSKFTQPVADVLT         QDFSQDPSKFTQP
11  QDFSQDPSKFTQPVADVLTN         QDFSQDPSKFTQP